NUM_WORKER_NODES=2
IP_NW="10.1.0."
IP_START=10

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
    SHELL
    config.vm.box = "bento/ubuntu-20.04-arm64"
    config.vm.box_version = "202306.30.0"
    config.vm.box_check_update = true

    config.vm.define "master" do |master|
      master.vm.hostname = "master-node"
      master.vm.network "private_network", ip: IP_NW + "#{IP_START}"

      master.vm.provider "parallels" do |vb|
          vb.memory = 8196
          vb.cpus = 2
      end

      master.vm.provider "vmware_desktop" do |vmware|
          vmware.memory = 8196
          vmware.cpus = 2
      end

      master.vm.provision "shell", path: "common.sh"
    end
  end